### ISSUE TITLE
Why does buddy.auth/authenticated use boolean?

### ISSUE THREAD

**Issue by deadghost** [funcool/buddy-auth#12]
https://github.com/funcool/buddy-auth/blob/master/src/clojure/buddy/auth.clj#L20

I notice you wrap the expression with `boolean` and wonder if there's any particular reason you did this since anything not `nil` is a truthy value anyways.

**Comment by niwinz** [comment]
Because this function intend to be predicate that returns a truly boolean value. In my opinon, retuning the identity and treat it as logical bool is a wrong approach, because the function is an predicate. Seems non-semantic that a predicate instead of returning a true o false, returns the value of `:identity` from request.

**Comment by deadghost** [comment]
Fair enough.
