### ISSUE TITLE
http-basic with access rules?

### ISSUE THREAD

**Issue by spiffytech** [funcool/buddy-auth#35]
I started with `wrap-authorization` with the httpbasic handler, which worked well as long as I peppered my controllers with `authenticated?` checks.  If unauthenticated, I was prompted for my httpbasic credentials, and only got an "unauthorized" error if I refused to provide them.

Now I'm trying to switch to `wrap-access-rules` so I can protect URLs with a regex and DRY up my auth config. But now everything returns my `on-error` response, and I can't figure out how to prompt for httpbasic credentials when I receive an authentication failure. 

Does buddy-auth include a way to this? Can the docs please get updated with an example?

**Comment by spiffytech** [comment]
I figured it out! My app handler definition needs to look like this:

```
(def auth-backend
  (http-basic-backend {:realm "MySite" :authfn authn-fn}))

(def handler (->
  app
  (wrap-access-rules {:rules authz-rules})
  (wrap-authorization auth-backend)
  (wrap-authentication auth-backend)
))
```

It's all about layers on an onion: First you have to set your authz rules with `wrap-access-rules`. Then you set your authz failure handler with `wrap-authorization`, since the `http-basic-backend` includes rules for handling auth failure (namely, throwing up the HTTP Basic Auth prompt). Then you add `wrap-authentication` so your app knows what to do when a user submits their auth credentials.

Each of these middlewares wraps the results of the previous by adding additional behavior on top of the return value from the previous middleware layer. Consequently, they must be inserted in the correct order to work.

I'd appreciate if the correct arrangement + ordering of authn/authz layers made its way into the buddy documentation.

**Comment by niwinz** [comment]
hi @spiffytech. Sorry for my late response. I was so busy...

If you attach `on-error` handler to the access-rule/rules, the responsability to return the appropiate response is delegated to it. TL.DR: setting on-error handler your are overwritting the backend specific logic with yours logic.

In respect of the backend ordering, the correct order is:

```
(-> app
    (wrap-access-rules {:rules authz-rules})
    (wrap-authentication auth-backend)
    (wrap-authorization auth-backend))
```

The `wrap-authorization` is the first middleware because its responsability is catch unauthorized exceptions that can be raised by `wrap-authentication` and `wrap-access-rules` middlewares.

I hope you find this useful.
